name: ragnebalteskard
favicon: null
layout_spectrum: 0.56687
typography_spectrum: 0.17779
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#445066'
    - '#bcb1b5'
    - '#7e7f8b'
    - '#903e1f'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
